version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
        - name: blank-imports
        - name: error-return
        - name: error-strings
        - name: unreachable-code

run:
  timeout: 3m
